/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IJuryOracle {
  export type VoteInputStruct = {
    payoutBps: BigNumberish;
    confidenceBps: BigNumberish;
    rationaleHash: BytesLike;
    stakeTier: BigNumberish;
    locality: BigNumberish;
    expertise: BigNumberish;
  };

  export type VoteInputStructOutput = [
    payoutBps: bigint,
    confidenceBps: bigint,
    rationaleHash: string,
    stakeTier: bigint,
    locality: bigint,
    expertise: bigint
  ] & {
    payoutBps: bigint;
    confidenceBps: bigint;
    rationaleHash: string;
    stakeTier: bigint;
    locality: bigint;
    expertise: bigint;
  };
}

export interface IJuryOracleInterface extends Interface {
  getFunction(
    nameOrSignature: "getPanel" | "getVote" | "selectPanel" | "submitVote"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PanelSelected" | "VoteCast"): EventFragment;

  encodeFunctionData(functionFragment: "getPanel", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "selectPanel",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitVote",
    values: [BytesLike, IJuryOracle.VoteInputStruct]
  ): string;

  decodeFunctionResult(functionFragment: "getPanel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "selectPanel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitVote", data: BytesLike): Result;
}

export namespace PanelSelectedEvent {
  export type InputTuple = [
    claimId: BytesLike,
    jurors: AddressLike[],
    seed: BytesLike
  ];
  export type OutputTuple = [claimId: string, jurors: string[], seed: string];
  export interface OutputObject {
    claimId: string;
    jurors: string[];
    seed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    claimId: BytesLike,
    juror: AddressLike,
    payoutBps: BigNumberish,
    confidenceBps: BigNumberish,
    rationaleHash: BytesLike
  ];
  export type OutputTuple = [
    claimId: string,
    juror: string,
    payoutBps: bigint,
    confidenceBps: bigint,
    rationaleHash: string
  ];
  export interface OutputObject {
    claimId: string;
    juror: string;
    payoutBps: bigint;
    confidenceBps: bigint;
    rationaleHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IJuryOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IJuryOracle;
  waitForDeployment(): Promise<this>;

  interface: IJuryOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPanel: TypedContractMethod<
    [claimId: BytesLike],
    [[string[], bigint] & { jurors: string[]; deadline: bigint }],
    "view"
  >;

  getVote: TypedContractMethod<
    [claimId: BytesLike, juror: AddressLike],
    [
      [IJuryOracle.VoteInputStructOutput, boolean] & {
        input: IJuryOracle.VoteInputStructOutput;
        exists: boolean;
      }
    ],
    "view"
  >;

  selectPanel: TypedContractMethod<
    [claimId: BytesLike, seed: BytesLike],
    [void],
    "nonpayable"
  >;

  submitVote: TypedContractMethod<
    [claimId: BytesLike, input: IJuryOracle.VoteInputStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPanel"
  ): TypedContractMethod<
    [claimId: BytesLike],
    [[string[], bigint] & { jurors: string[]; deadline: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [claimId: BytesLike, juror: AddressLike],
    [
      [IJuryOracle.VoteInputStructOutput, boolean] & {
        input: IJuryOracle.VoteInputStructOutput;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "selectPanel"
  ): TypedContractMethod<
    [claimId: BytesLike, seed: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitVote"
  ): TypedContractMethod<
    [claimId: BytesLike, input: IJuryOracle.VoteInputStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PanelSelected"
  ): TypedContractEvent<
    PanelSelectedEvent.InputTuple,
    PanelSelectedEvent.OutputTuple,
    PanelSelectedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "PanelSelected(bytes32,address[],bytes32)": TypedContractEvent<
      PanelSelectedEvent.InputTuple,
      PanelSelectedEvent.OutputTuple,
      PanelSelectedEvent.OutputObject
    >;
    PanelSelected: TypedContractEvent<
      PanelSelectedEvent.InputTuple,
      PanelSelectedEvent.OutputTuple,
      PanelSelectedEvent.OutputObject
    >;

    "VoteCast(bytes32,address,uint16,uint16,bytes32)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
