version: '3.8'

services:
  ai-service:
    build: .
    container_name: guardchain_ai_service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - LOG_LEVEL=INFO
      - BACKEND_API_KEY=guardchain_dev_key_2024
      - ADMIN_API_KEY=guardchain_admin_key_2024
      - TEST_API_KEY=guardchain_test_key_2024
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - guardchain-network

networks:
  guardchain-network:
    external: true 